### ISSUE TITLE
two 'print' rows in exception handle

### ISSUE THREAD

**Issue by stepikogs** [rfateam2/rfa#5]
https://github.com/rfateam2/rfa/blob/nixer/rfaUtils.py#L21

two 'print' rows look like leftover. Guess, it should be single 'print' here.

**Comment by rfateam2** [comment]
https://github.com/stepikogs 
plz, open Nixer's brunch https://github.com/rfateam2/rfa/commits/nixer, last commit.
Add your comment to piece of code. Thx!
