### ISSUE TITLE
We have to handled path to log_file to close log_file

### ISSUE THREAD

**Issue by korvinca** [rfateam2/rfa#9]
log = get_log()
return
`(<open file '/Users/koroli/workspace/rfa/logs/testrun_20161026_19:50.log', mode 'a' at 0x102c901e0>, '/Users/koroli/workspace/rfa/logs/testrun_20161026_19:50.log')`
1. mode of log_file
2. path to log_file

We have to to pass a value of "path to log_file"

**Comment by rfateam2** [comment]
https://github.com/rfateam2/rfa/pull/10
https://github.com/rfateam2/rfa/pull/11
